name = "cs-addon"
main = "src/index.js"
compatibility_date = "2024-03-21"

[[d1_databases]]
binding = "CS_DB"
database_name = "aether-db"
database_id = "3e44e5b3-a0f6-41fa-9e11-6cb7bf3fb0d0"

[[kv_namespaces]]
binding = "CS_KV"
id = "02640e74e3a148868419fa6fb34907d0"
